import React, { useState } from 'react';
import { Presentation, FileText, Network, Sparkles, Download, Copy, Check } from 'lucide-react';
import { SpotlightCard } from '../components/ui/SpotlightCard';

export const ReportGeneratorPage: React.FC = () => {
  const [reportType, setReportType] = useState<'PDF' | 'PPT' | 'MINDMAP'>('PDF');
  const [copied, setCopied] = useState(false);

  const reports: Record<'PDF' | 'PPT' | 'MINDMAP', string> = {
    PDF: `EXECUTIVE DOCUMENT INTELLIGENCE SUMMARY REPORT
Period: August 2026
Generated by: IntelliDoc AI Engine v2026

1. EXECUTIVE SUMMARY
In August 2026, 14,823 enterprise documents were processed with an average extraction accuracy of 98.4%. Processing latency averaged 420ms per document across Vision OCR and Gemini 2.5 Pro inference pipelines.

2. FRAUD & COMPLIANCE
- Flagged Anomaly Count: 14 documents (0.09%)
- Mathematical Formula Verification: 100% passed
- Fraud Prevention Savings: $42,500.00 USD

3. KEY INSIGHTS & RECOMMENDATIONS
- Auto-renew Delaware MSA contracts 60 days prior to expiration.
- Vendor Acme Cloud Dynamics verified with $14,850 total billable amount.`,

    PPT: `SLIDE DECK OUTLINE: ENTERPRISE DOCUMENT INTELLIGENCE Q3 2026

SLIDE 1: Title & Executive Overview
- Title: IntelliDoc AI Q3 Operational Briefing
- Speaker: Alex Rivera, Principal AI Architect

SLIDE 2: Processing Metrics
- Total Documents Parsed: 14,823 files
- Accuracy Score: 98.4% Average Precision
- Average Throughput: 420ms per document

SLIDE 3: Financial & Fraud Guard Performance
- Total Subtotal Processed: $18.4M USD
- Fraudulent Submissions Blocked: $42,500.00 USD
- Anomaly Rate: 0.09% across enterprise ingestions

SLIDE 4: Next Steps & AI Roadmap
- Expand Model Context Protocol (MCP) integrations
- Deploy zero-data retention WebAssembly offline model`,

    MINDMAP: `DOCUMENT INTELLIGENCE KNOWLEDGE MINDMAP

[Central Node: IntelliDoc AI Enterprise Platform]
   ├── [Ingestion Engine]
   │      ├── PDF / Scanned Images / DOCX / CSV
   │      ├── Multi-Modal Vision OCR
   │      └── Zip Archive Batch Parser
   ├── [AI Multi-Agent Core]
   │      ├── Gemini 2.0 Flash Reasoning
   │      ├── Math & GST Integrity Validator
   │      └── Fraud Guard Anomaly Detection
   └── [RAG & Vector Knowledge Base]
          ├── Semantic Vector Search
          ├── Real-Time Citations
          └── Automated Executive Report Generator`,
  };

  const currentReport = reports[reportType];

  const handleCopy = () => {
    navigator.clipboard.writeText(currentReport);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const ext = reportType === 'PPT' ? 'txt' : reportType === 'MINDMAP' ? 'txt' : 'txt';
    const blob = new Blob([currentReport], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `IntelliDoc_${reportType}_Report_2026.${ext}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="p-4 lg:p-8 space-y-8 max-w-6xl mx-auto text-left">
      <div>
        <div className="flex items-center space-x-2 mb-1">
          <h1 className="text-2xl font-extrabold text-slate-100">AI Executive Business Report & Deck Generator</h1>
          <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-cyan-950 text-cyan-400 border border-cyan-500/40">
            PDF • PPT • Mind Maps
          </span>
        </div>
        <p className="text-xs text-slate-400">Generate executive business summaries, PowerPoint presentation slides, and visual mind maps instantly.</p>
      </div>

      {/* Format Selector Pills */}
      <div className="flex space-x-3">
        {[
          { type: 'PDF' as const, label: 'Executive PDF Summary', icon: FileText },
          { type: 'PPT' as const, label: 'PowerPoint Deck Outline', icon: Presentation },
          { type: 'MINDMAP' as const, label: 'Visual Mind Map Outline', icon: Network },
        ].map((item) => {
          const Icon = item.icon;
          const isActive = reportType === item.type;
          return (
            <button
              key={item.type}
              onClick={() => setReportType(item.type)}
              className={`px-4 py-2 rounded-xl text-xs font-bold transition-all flex items-center space-x-2 cursor-pointer ${
                isActive
                  ? 'bg-cyan-500 text-slate-950 shadow-md shadow-cyan-500/20'
                  : 'bg-slate-900 text-slate-400 hover:text-slate-200 border border-slate-800'
              }`}
            >
              <Icon className="w-4 h-4" />
              <span>{item.label}</span>
            </button>
          );
        })}
      </div>

      {/* Report Output Box */}
      <SpotlightCard className="p-6 space-y-4">
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <span className="text-xs font-bold text-cyan-400 flex items-center space-x-1.5">
            <Sparkles className="w-4 h-4" />
            <span>AI Generated {reportType} Executive Output</span>
          </span>
          <div className="flex items-center space-x-2">
            <button
              onClick={handleCopy}
              className="px-3.5 py-1.5 rounded-xl bg-slate-900 hover:bg-slate-800 border border-slate-800 text-xs font-semibold text-slate-200 transition-colors flex items-center space-x-1.5 cursor-pointer"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5 text-cyan-400" />}
              <span>{copied ? 'Copied!' : 'Copy Content'}</span>
            </button>
            <button
              onClick={handleDownload}
              className="px-3.5 py-1.5 rounded-xl bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold text-xs transition-colors flex items-center space-x-1.5 cursor-pointer shadow-md shadow-cyan-500/20"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download {reportType}</span>
            </button>
          </div>
        </div>

        <pre className="text-xs font-mono text-slate-300 bg-slate-950 p-4 rounded-xl border border-slate-800 leading-relaxed whitespace-pre-line overflow-x-auto max-h-[380px]">
          {currentReport}
        </pre>
      </SpotlightCard>
    </div>
  );
};
